name: tut_chat_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_login: ^4.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  shared_preferences: ^2.0.15
  http: ^0.13.4

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
  - assets/
  - assets/icon/



  uses-material-design: true
